#!/usr/bin/env python
#
# Pablo Munoz (c) 2018
#
# Example use of fortran wrapper
#
import numpy as np
from fib import fib, matmul, transpose

# Print doc generated by f2py
print(fib.__doc__)

# Use
print(fib(10))
print()

# Use matrix multiplication
N = 100
A = np.eye(N)
B = np.random.rand(N, N)

if not np.testing.assert_array_equal(np.dot(A, B), B):
    print('PYTHON  matrix multiplication test OK')

if not np.testing.assert_array_equal(matmul(A, B, N, N, N), B):
    print('FORTRAN OK matrix multiplication explicit dimension test ')

if not np.testing.assert_array_equal(matmul(A, B), B):
    print('FORTRAN OK matrix multiplication implicit dimension test ')

if not np.testing.assert_array_equal(transpose(A), A):
    print('FORTRAN OK matrix identity transpose is itself test ')

if not np.testing.assert_array_equal(transpose(transpose(B)), B):
    print('FORTRAN OK test:: transpose**2 === identity ')

if transpose(np.random.rand(100,200)).shape == (200, 100):
    print('FORTRAN OK transpose shape test ')

