#!/usr/bin/env python
#
# Pablo Munoz (c) 2018
#
# Example use of fortran wrapper
#
from numpy import zeros
from fib import fib

# Print doc generated by f2py
print(fib.__doc__)

# Use
print(fib(10))
